#!/bin/bash

while [[ $# == 0 ]]
do
    echo ""
    echo "  Usage: keef [command]"
    echo ""
    echo "      data        begins the data pipeline"
    echo "      test        Runs tests"
    echo ""
    break
done

# Parse argument
while [[ $# == 1 ]]
do
    arg="$1"
    case $arg in
        data)
            python pipeline/tasks.py
            shift
            ;;
	test)
	    nosetests --with-specplugin
	    shift
	    ;;
    	*)
            echo "" 
            echo "  Argument '$arg' not recognized"
            ./keef
            shift
            ;;
    esac
    break
done
